"""API Knowledge Graph — built by INTROSPECTING installed packages (ASE + mtagent).

Why introspection (not doc scraping): docs.ase-lib.org is generated by Sphinx autodoc
FROM the package docstrings, so introspection yields the same signatures + descriptions,
locally and version-matched. It is exact, complete, and regenerates on upgrade. The same
mechanism covers mtagent's own builders, so LLM-proposed snippets are validated against
the REAL signatures of everything they are allowed to call.

The KG stores one entry per public function / class / method, each with its real
signature (parameters, kinds, defaults) and docstring summary. This grounds snippet
generation (evidence packs) and powers the AST-based Gate 1 validator (ase_validate.py).
"""
from __future__ import annotations

import importlib
import inspect
from dataclasses import dataclass, field

import networkx as nx

# Module scope, following the docs.ase-lib.org reference structure.
MODULES = [
    "ase", "ase.atoms", "ase.build", "ase.cluster", "ase.io",
    "ase.optimize", "ase.constraints", "ase.geometry", "ase.cell",
    "ase.neighborlist", "ase.data",
    # MD-related (execution deferred, but covered in the KG now):
    "ase.md", "ase.md.velocitydistribution", "ase.md.langevin", "ase.md.verlet",
    "ase.calculators.emt", "ase.calculators.lj",
]

# mtagent's own builder/combiner modules — snippets may call these too.
MTAGENT_MODULES = [
    "mtagent.pubchem", "mtagent.nanoparticle", "mtagent.wulff", "mtagent.hydroxylate",
    "mtagent.nanostructures", "mtagent.solvent", "mtagent.packing", "mtagent.cluster",
    "mtagent.assemble",
]


@dataclass
class Param:
    name: str
    kind: str            # positional_only | positional_or_keyword | keyword_only | var_positional | var_keyword
    has_default: bool


@dataclass
class ApiEntry:
    qualname: str        # accessible path, e.g. "ase.build.bulk"
    kind: str            # function | class | method
    module: str
    signature: str
    params: list[Param] = field(default_factory=list)
    doc: str = ""

    @property
    def keyword_names(self) -> set[str]:
        return {p.name for p in self.params
                if p.kind in ("positional_or_keyword", "keyword_only")}

    @property
    def accepts_kwargs(self) -> bool:
        return any(p.kind == "var_keyword" for p in self.params)

    @property
    def accepts_varargs(self) -> bool:
        return any(p.kind == "var_positional" for p in self.params)

    @property
    def max_positional(self) -> int:
        return sum(1 for p in self.params
                   if p.kind in ("positional_only", "positional_or_keyword"))


_KIND = {
    inspect.Parameter.POSITIONAL_ONLY: "positional_only",
    inspect.Parameter.POSITIONAL_OR_KEYWORD: "positional_or_keyword",
    inspect.Parameter.KEYWORD_ONLY: "keyword_only",
    inspect.Parameter.VAR_POSITIONAL: "var_positional",
    inspect.Parameter.VAR_KEYWORD: "var_keyword",
}


def _params(obj) -> tuple[str, list[Param]] | None:
    try:
        sig = inspect.signature(obj)
    except (ValueError, TypeError):
        return None
    params = [Param(p.name, _KIND.get(p.kind, "positional_or_keyword"),
                    p.default is not inspect.Parameter.empty)
              for p in sig.parameters.values()]
    return str(sig), params


def _summary(obj) -> str:
    doc = inspect.getdoc(obj) or ""
    return doc.strip().split("\n\n")[0].replace("\n", " ")[:200]


class ASEKnowledgeGraph:
    """Introspection-built, queryable API knowledge graph (ASE by default)."""

    def __init__(self, modules: list[str] | None = None,
                 prefixes: tuple[str, ...] = ("ase",)) -> None:
        self.entries: dict[str, ApiEntry] = {}
        self.graph = nx.DiGraph()
        self.short_index: dict[str, set[str]] = {}     # short name -> {qualnames}
        self.atoms_methods: set[str] = set()
        self.method_names: set[str] = set()
        self.prefixes = prefixes
        self._build(modules or MODULES)

    def _add(self, qualname: str, kind: str, module: str, obj) -> None:
        pr = _params(obj)
        sig, params = (pr[0], pr[1]) if pr else ("(...)", [])
        entry = ApiEntry(qualname, kind, module, sig, params, _summary(obj))
        self.entries[qualname] = entry
        short = qualname.rsplit(".", 1)[-1]
        self.short_index.setdefault(short, set()).add(qualname)
        self.graph.add_node(qualname, kind=kind, module=module)
        self.graph.add_edge(module, qualname, relation="contains")

    def _build(self, modules: list[str]) -> None:
        for modname in modules:
            try:
                mod = importlib.import_module(modname)
            except Exception:
                continue
            self.graph.add_node(modname, kind="module", module=modname)
            for name, obj in inspect.getmembers(mod):
                if name.startswith("_"):
                    continue
                origin = getattr(obj, "__module__", "") or ""
                if not origin.startswith(self.prefixes):
                    continue                                   # skip re-exported numpy etc.
                qual = f"{modname}.{name}"
                if inspect.isfunction(obj) or inspect.isbuiltin(obj):
                    self._add(qual, "function", modname, obj)
                elif inspect.isclass(obj):
                    self._add(qual, "class", modname, obj)
                    for mname, meth in inspect.getmembers(obj, inspect.isfunction):
                        if mname.startswith("_"):
                            continue
                        self.method_names.add(mname)
                        mqual = f"{qual}.{mname}"
                        self._add(mqual, "method", qual, meth)
                        if name == "Atoms":
                            self.atoms_methods.add(mname)

    # -- queries
    def get(self, qualname: str) -> ApiEntry | None:
        return self.entries.get(qualname)

    def stats(self) -> dict:
        kinds: dict[str, int] = {}
        for e in self.entries.values():
            kinds[e.kind] = kinds.get(e.kind, 0) + 1
        return {"entries": len(self.entries), "modules": len(MODULES),
                "graph_nodes": self.graph.number_of_nodes(),
                "atoms_methods": len(self.atoms_methods), "by_kind": kinds}

    def retrieve(self, query: str, limit: int = 8) -> list[ApiEntry]:
        q = query.lower()
        scored = []
        for e in self.entries.values():
            name = e.qualname.rsplit(".", 1)[-1].lower()
            score = (2 if q in name else 0) + (1 if q in e.doc.lower() else 0)
            if score:
                scored.append((score, e))
        scored.sort(key=lambda x: (-x[0], x[1].qualname))
        return [e for _, e in scored[:limit]]
