"""Moltemplate Knowledge Graph — content, extracted from the official manual.

Source: moltemplate_manual.pdf (data/refs/), primarily the §3 "Quick reference"
(§3.1 commands, §3.2 $/@ variables, §3.3 coordinate transformations) plus §5, §7,
§8, §9, §10. Each construct records the manual section it came from.

Design: plain data so it is easy to read/extend. `geometry_ok=False` marks
force-field / simulation constructs that are omitted in our geometry-only mode
(retrieval still knows about them so Gate 1 never false-rejects valid .lt).
"""
from __future__ import annotations

# --- Commands / keywords (§3.1) ----------------------------------------------
COMMANDS = {
    "new":               "Instantiate a copy of a molecule type (arrays: new Mol[N]).",
    "delete":            "Delete a molecule/atom/bond/angle/dihedral/improper (or a range).",
    "write":             "Emit per-instance lines into a 'Data '/'In ' section (every new).",
    "write_once":        "Emit shared lines into a section exactly once.",
    "import":            "Insert another file's contents, preventing circular inclusion.",
    "include":           "Insert another file's contents here (quotes optional).",
    "inherits":          "Define an object type from one or more existing types (multiple OK).",
    "replace":           "Alias one @variable to another (both need '@' prefix).",
    "category":          "Create a counter-variable category starting at i0, step Δ.",
    "create_var":        "Create a molecule-specific $ variable (shared molecule-IDs).",
    "create_static_var": "Create a molecule-specific @ variable (shared @atom types).",
    "push":              "Push a coordinate transform onto the stack (applied to later new).",
    "pop":               "Pop the last transform off the stack.",
    "random":            "Build a random array from types with probabilities/exact counts.",
}

# --- Coordinate transformations (§3.3) ---------------------------------------
# 'arities' = the SET of allowed argument counts (several forms per transform).
TRANSFORMS = {
    "move":   {"arities": {3},          "desc": "Add (x,y,z) to every atom's coordinates."},
    "rot":    {"arities": {4, 7},       "desc": "Rotate θ about axis (x,y,z) through origin, "
                                                 "or through point (x0,y0,z0) with 7 args."},
    "rotvv":  {"arities": {6, 9},       "desc": "Rotate mapping vector v1->v2 (optional pivot x0,y0,z0)."},
    "scale":  {"arities": {1, 3, 4, 6}, "desc": "Scale uniform/per-axis, optional fixed point."},
    "quat":   {"arities": {4, 7},       "desc": "Rotate by quaternion (a,b,c,d), optional pivot."},
    "matrix": {"arities": {9},          "desc": "General 3x3 linear transform (row-major)."},
}

# Variable-formatting methods used inside ${...}/@{...} (§3.2) — NOT transforms.
FORMAT_METHODS = {"rjust", "ljust"}

# Doc metavariables (placeholders for 'some transformation') — not real commands.
PLACEHOLDERS = {"xform", "xform1", "xform2", "xf1", "xf2"}

# --- Data / In sections (§5.3, §7, §9) ---------------------------------------
# Names beginning "Data "/"In " are inserted into the LAMMPS data file / input script.
DATA_SECTIONS = {
    # topology + coordinates (geometry-relevant)
    "Data Atoms":          {"geometry_ok": True,  "columns": "$atom:id $mol:id @atom:type q x y z (full)"},
    "Data Bonds":          {"geometry_ok": True,  "columns": "$bond:id @bond:type $atom:a $atom:b"},
    "Data Bond List":      {"geometry_ok": True,  "columns": "$bond:id $atom:a $atom:b (no bond type)"},
    "Data Angles":         {"geometry_ok": True,  "columns": "$angle:id @angle:type a b c"},
    "Data Dihedrals":      {"geometry_ok": True,  "columns": "$dihedral:id @dihedral:type a b c d"},
    "Data Impropers":      {"geometry_ok": True,  "columns": "$improper:id @improper:type a b c d"},
    "Data Masses":         {"geometry_ok": True,  "columns": "@atom:type mass"},
    "Data Boundary":       {"geometry_ok": True,  "columns": "xlo xhi / ylo yhi / zlo zhi"},
    "Data Velocities":     {"geometry_ok": True,  "columns": "$atom:id vx vy vz"},
    "Data Ellipsoids":     {"geometry_ok": True,  "columns": "$atom:id shapex shapey shapez qw qi qj qk"},
    "In Charges":          {"geometry_ok": True,  "columns": "set atom charge (per-atom charges)"},
    # topology generated by type (force-field workflow)
    "Data Bonds By Type":     {"geometry_ok": False, "note": "auto-generate bonds from @atom types."},
    "Data Angles By Type":    {"geometry_ok": False, "note": "auto-generate angles from @atom types."},
    "Data Dihedrals By Type": {"geometry_ok": False, "note": "auto-generate dihedrals from types."},
    "Data Impropers By Type": {"geometry_ok": False, "note": "auto-generate impropers from types."},
    "Data Charge By Bond":    {"geometry_ok": False, "note": "bond-increment charges."},
    # force-field coefficients / init
    "In Init":               {"geometry_ok": False, "note": "units/atom_style/ff init; omit for geometry-only."},
    "In Settings":           {"geometry_ok": False, "note": "pair/bond/angle coeffs etc.; omit for geometry-only."},
    "Data Pair Coeffs":      {"geometry_ok": False, "note": "force-field pair parameters."},
    "Data PairIJ Coeffs":    {"geometry_ok": False, "note": "explicit i-j pair parameters."},
    "Data Bond Coeffs":      {"geometry_ok": False, "note": "force-field bond parameters."},
    "Data Angle Coeffs":     {"geometry_ok": False, "note": "force-field angle parameters."},
    "Data Dihedral Coeffs":  {"geometry_ok": False, "note": "force-field dihedral parameters."},
    "Data Improper Coeffs":  {"geometry_ok": False, "note": "force-field improper parameters."},
}

# --- Variable sigils (§3.2): $ = per-instance id, @ = shared type -------------
VARIABLES = {
    "$atom": "unique atom ID in this molecule", "@atom": "atom type number",
    "$bond": "unique bond ID", "@bond": "bond type number",
    "$angle": "unique angle ID", "@angle": "angle type number",
    "$dihedral": "unique dihedral ID", "@dihedral": "dihedral type number",
    "$improper": "unique improper ID", "@improper": "improper type number",
    "$mol": "molecule ID (name optional; default '.'; also $mol:... for parent)",
}

# --- Path / scope tokens (§10.6) ---------------------------------------------
PATH_TOKENS = {
    "../":   "reference the parent object's namespace",
    ".../":  "ellipsis: search outward through enclosing scopes",
    "$mol:.": "the molecule-ID of the current object",
}

# --- Edges: (source, target, relation) ---------------------------------------
# relations: requires | force_field_for | attaches_to | writes | generates | contains
EDGES = [
    ("Data Bonds", "Data Atoms", "requires"),
    ("Data Bond List", "Data Atoms", "requires"),
    ("Data Angles", "Data Atoms", "requires"),
    ("Data Dihedrals", "Data Atoms", "requires"),
    ("Data Impropers", "Data Atoms", "requires"),
    ("Data Bond Coeffs", "Data Bonds", "force_field_for"),
    ("Data Angle Coeffs", "Data Angles", "force_field_for"),
    ("Data Dihedral Coeffs", "Data Dihedrals", "force_field_for"),
    ("Data Bonds By Type", "Data Bonds", "generates"),
    ("Data Angles By Type", "Data Angles", "generates"),
    ("In Settings", "Data Bond Coeffs", "contains"),
    ("move", "new", "attaches_to"),
    ("rot", "new", "attaches_to"),
    ("rotvv", "new", "attaches_to"),
    ("scale", "new", "attaches_to"),
    ("quat", "new", "attaches_to"),
    ("matrix", "new", "attaches_to"),
    ("push", "new", "attaches_to"),
    ("inherits", "new", "attaches_to"),
    ("write", "Data Atoms", "writes"),
    ("write", "Data Bonds", "writes"),
    ("write_once", "Data Masses", "writes"),
    ("write_once", "Data Boundary", "writes"),
]

# --- Conditions: retrieval gates / recipes (§6, §7, §8, §9) -------------------
CONDITIONS = {
    "geometry_only": {
        "triggers": ["geometry", "no force field", "structure only", "coordinates"],
        "include": ["Data Atoms", "Data Bonds", "Data Bond List", "Data Masses", "Data Boundary"],
        "exclude": ["In Init", "In Settings", "Data Bond Coeffs", "Data Angle Coeffs",
                    "Data Pair Coeffs", "Data Bonds By Type", "Data Angles By Type"],
        "note": "Emit topology + coordinates only; run moltemplate.sh with -nocheck.",
    },
    "reusable_placement": {
        "triggers": ["shell", "around", "coat", "coated", "surround", "disperse", "random"],
        "include": ["new", "move", "rot"],
        "exclude": [],
        "note": "Define the molecule once; instantiate N times with .rot(...).move(...).",
    },
    "regular_array": {
        "triggers": ["array", "lattice", "grid", "periodic", "crystal", "superlattice"],
        "include": ["new", "move"],
        "exclude": [],
        "note": "Array instancing: new Mol[N].move(...); slices [*]/[i-j] customize copies.",
    },
    "random_mixture": {
        "triggers": ["mixture", "random", "vacancy", "vacancies", "blend"],
        "include": ["new", "random", "delete"],
        "exclude": [],
        "note": "Use new random([...],[probs or counts],seed)[N]; delete for vacancies.",
    },
    "rigid_core": {
        "triggers": ["nanoparticle", "core", "cluster", "slab", "surface", "particle"],
        "include": ["Data Atoms"],
        "exclude": [],
        "note": "Emit the core as one object with explicit coordinates; no bonds for a metal.",
    },
    "set_boundary": {
        "triggers": ["box", "boundary", "cell", "periodic"],
        "include": ["Data Boundary"],
        "exclude": [],
        "note": "Define the simulation box via write_once(\"Data Boundary\").",
    },
    "bonded_molecule": {
        "triggers": ["molecule", "water", "solvent", "ligand", "acid", "chain", "polymer"],
        "include": ["Data Atoms", "Data Bonds", "Data Masses"],
        "exclude": [],
        "note": "A molecule carries atoms + intramolecular bonds + masses.",
    },
    "composition": {
        "triggers": ["inherit", "inherits", "based on", "extend", "nesting", "subunit", "monomer"],
        "include": ["new", "inherits", "import"],
        "exclude": [],
        "note": "Build big molecules from pieces via new, inherits, and import.",
    },
}
